// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_app/test/data/repositories/device_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:flutter_app/core/resources/api_service.dart' as _i3;
import 'package:flutter_app/core/resources/service_locator.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiService_1 extends _i1.SmartFake implements _i3.ApiService {
  _FakeApiService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<T> request<T>({
    required String? url,
    required _i3.HttpMethod? method,
    required T Function(dynamic)? builder,
    Map<String, dynamic>? queryParams,
    dynamic requestBody,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [],
          {
            #url: url,
            #method: method,
            #builder: builder,
            #queryParams: queryParams,
            #requestBody: requestBody,
          },
        ),
        returnValue: _i4.ifNotNull(
              _i4.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #request,
                  [],
                  {
                    #url: url,
                    #method: method,
                    #builder: builder,
                    #queryParams: queryParams,
                    #requestBody: requestBody,
                  },
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.method(
                #request,
                [],
                {
                  #url: url,
                  #method: method,
                  #builder: builder,
                  #queryParams: queryParams,
                  #requestBody: requestBody,
                },
              ),
            ),
      ) as _i2.Future<T>);
}

/// A class which mocks [ServiceLocator].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceLocator extends _i1.Mock implements _i5.ServiceLocator {
  MockServiceLocator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ApiService apiService() => (super.noSuchMethod(
        Invocation.method(
          #apiService,
          [],
        ),
        returnValue: _FakeApiService_1(
          this,
          Invocation.method(
            #apiService,
            [],
          ),
        ),
      ) as _i3.ApiService);
}
